apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: devpassword

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dev
data:
  MYSQL_DATABASE: devdb

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-dev
  namespace: dev
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0

    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_ROOT_PASSWORD

    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: mysql-config
          key: MYSQL_DATABASE

    ports:
    - containerPort: 3306