apiVersion: v1
kind: Service
metadata:
  name: svc-headless-web
spec:
  type: NodePort
  selector:
    app: demo-headless      # same pods as the headless service
  ports:
  - name: nginx-http
    port: 80
    targetPort: http
    nodePort: 30090
  - name: python-http
    port: 8080
    targetPort: python
    nodePort: 30091
