apiVersion: v1
kind: Pod

metadata:

  name: dynamic-demo

spec:

  containers:

  - image: nginx

    name: nginx

    volumeMounts:

    - mountPath: /data

      name: storage

  volumes:

  - name: storage

    persistentVolumeClaim:

      claimName: dynamic-pvc