apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: dev
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    env:
    - name: REDIS_PASSWORD
      value: "mysecretpassword"

