apiVersion: v1
kind: Service
metadata:
  name: mount-demo-svc
  labels:
    app: mount-demo
spec:
  type: NodePort
  selector:
    app: mount-demo        # matches the Pod label
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081        # open http://<node-ip>:30081  (range 30000-32767)
