apiVersion: v1
kind: Service

metadata:
  name: blueforge

spec:
  selector:
    app: blueforge

  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080

  type: NodePort