apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hpa
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-hpa

  template:
    metadata:
      labels:
        app: nginx-hpa

    spec:
      containers:
      - name: nginx
        image: nginx:alpine

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: 100m
            memory: 64Mi

          limits:
            cpu: 200m
            memory: 128Mi