apiVersion: v1
kind: Pod
metadata:
  name: backend-1
  labels:
    app: backendx
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - backendx
        topologyKey: kubernetes.io/hostname
  containers:
    - name: nginx
      image: nginx

