apiVersion: v1
kind: Service

metadata:
  name: fancy-frontend-lb

spec:

  type: LoadBalancer

  selector:
    app: fancy-frontend

  ports:

    - name: http

      protocol: TCP

      port: 80

      targetPort: 80