# =============================================================================
# webapp in the PROD namespace
# -----------------------------------------------------------------------------
# Identical to dev except the namespace and the echo text.
#
#   kubectl apply -f 04-webapp-prod.yaml
#   kubectl get pod,svc -n prod
# =============================================================================
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: prod
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: hashicorp/http-echo
      args: ["-text=Hello From PROD"]
      ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
spec:
  selector:
    app: webapp
  ports:
    - port: 5678
      targetPort: 5678
