#!/bin/bash

mkdir -p frontend sidecar k8s

####################################
# FRONTEND
####################################

cat > frontend/app.py <<'EOF'
from flask import Flask, request, send_file
import os,time

app=Flask(__name__)

HTML="""
<html>
<body>
<h2>Hall Ticket Generator</h2>

<form action="/generate" method="post">

Username:<br>
<input name="username"><br><br>

Batch:<br>
<input name="batch"><br><br>

Course:<br>
<input name="course"><br><br>

<input type="submit" value="Generate PDF">

</form>
</body>
</html>
"""

@app.route("/")
def home():
    return HTML

@app.route("/generate",methods=["POST"])
def generate():

    username=request.form["username"]
    batch=request.form["batch"]
    course=request.form["course"]

    if os.path.exists("/shared/hallticket.pdf"):
        os.remove("/shared/hallticket.pdf")

    with open("/shared/request.txt","w") as f:
        f.write(f"{username}|{batch}|{course}")

    for i in range(30):

        if os.path.exists("/shared/hallticket.pdf"):
            return send_file(
                "/shared/hallticket.pdf",
                as_attachment=True
            )

        time.sleep(1)

    return "PDF Generation Failed"

app.run(host="0.0.0.0",port=8080)
EOF

cat > frontend/requirements.txt <<'EOF'
flask
EOF

cat > frontend/Dockerfile <<'EOF'
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY app.py .

EXPOSE 8080

CMD ["python","app.py"]
EOF

####################################
# SIDECAR
####################################

cat > sidecar/sidecar.py <<'EOF'
from reportlab.pdfgen import canvas
import os,time

while True:

    if os.path.exists("/shared/request.txt"):

        with open("/shared/request.txt") as f:
            data=f.read()

        username,batch,course=data.split("|")

        pdf="/shared/hallticket.pdf"

        c=canvas.Canvas(pdf)

        c.setFont("Helvetica-Bold",18)
        c.drawString(180,800,"HALL TICKET")

        c.setFont("Helvetica",12)
        c.drawString(100,730,f"Student : {username}")
        c.drawString(100,700,f"Batch : {batch}")
        c.drawString(100,670,f"Course : {course}")

        c.drawString(100,620,"Generated by Kubernetes Sidecar")

        c.save()

        os.remove("/shared/request.txt")

    time.sleep(2)
EOF

cat > sidecar/Dockerfile <<'EOF'
FROM python:3.11-slim

WORKDIR /app

COPY sidecar.py .

RUN pip install reportlab

CMD ["python","sidecar.py"]
EOF

####################################
# DEPLOYMENT
####################################

cat > k8s/deployment.yaml <<'EOF'
apiVersion: apps/v1
kind: Deployment

metadata:
  name: hallticket-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hallticket

  template:
    metadata:
      labels:
        app: hallticket

    spec:

      volumes:
      - name: shared-data
        emptyDir: {}

      containers:

      - name: frontend
        image: hallticket-frontend:v1
        imagePullPolicy: Never

        ports:
        - containerPort: 8080

        volumeMounts:
        - name: shared-data
          mountPath: /shared

      - name: pdf-sidecar
        image: hallticket-sidecar:v1
        imagePullPolicy: Never

        volumeMounts:
        - name: shared-data
          mountPath: /shared
EOF

####################################
# SERVICE
####################################

cat > k8s/service.yaml <<'EOF'
apiVersion: v1
kind: Service

metadata:
  name: hallticket-service

spec:
  type: NodePort

  selector:
    app: hallticket

  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
EOF

echo "PROJECT CREATED"