apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: prod
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: hashicorp/http-echo
    args:
    - "-text=Hello From PROD"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
spec:
  selector:
    app: webapp
  ports:
  - port: 5678
    targetPort: 5678