apiVersion: v1
kind: Pod

metadata:
  name: nginx-storage
  labels:
    app: nginx

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: azure-storage
      mountPath: /usr/share/nginx/html

  volumes:
  - name: azure-storage
    persistentVolumeClaim:
      claimName: azurefile-pvc
