name: Deploy Application to AKS

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: my-aks-rg
  AKS_CLUSTER: my-aks-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Connect to existing AKS cluster
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER }}

      # 4. Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # 5. Check AKS connection
      - name: Check AKS
        run: |
          echo "Connected to AKS:"
          kubectl cluster-info

          echo "AKS Nodes:"
          kubectl get nodes

      # 6. Deploy Kubernetes manifests
      - name: Deploy Application
        run: |
          echo "Deploying Kubernetes manifests..."

          kubectl apply -f 17aksdirectdeployment/

      # 7. Verify deployment
      - name: Verify Deployment
        run: |
          echo "Deployments:"
          kubectl get deployments

          echo "Pods:"
          kubectl get pods

          echo "Services:"
          kubectl get services